#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Elastification\BackupRestore\Command\BackupRunCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new BackupRunCommand());
$application->run();